[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["lib", "dependencies"]

auto_detect_remappings = false

[dependencies]
forge-std = "1.11.0"
"@openzeppelin-contracts" = "5.4.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
